import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :phoenix_demo, PhoenixDemoWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :phoenix_demo, PhoenixDemoWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# The local mail adapter needs no API client.
config :swoosh, :api_client, false

# Keep the emails in memory for the public mailbox page (see the router).
config :swoosh, :local, true

# A password hash of the default cost (12) takes about 0.6 s of CPU in
# WebAssembly, and a Worker has little CPU time. Cost 10 is 4 times faster.
config :bcrypt_elixir, log_rounds: 10

# Do not print debug messages in production
config :logger, level: :info

# On Cloudflare Workers, beam.com runs the VM with -Mea min (no allocators of
# ERTS), and erlang:memory/0 is not supported there. The default poller of
# telemetry_poller calls it, so it is off.
config :telemetry_poller, :default, false

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
